//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motormechs.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<bool> PickNDrop { get; set; }
    }
}
