//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motormechs.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Token { get; set; }
        public Nullable<bool> IsAdminCreated { get; set; }
        public Nullable<System.Guid> ForgetPasswordCode { get; set; }
        public Nullable<System.DateTime> ForgetPasswordDate { get; set; }
        public Nullable<bool> ForgetPasswordStatus { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
    }
}
