//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> SlotId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public string Message { get; set; }
        public Nullable<System.TimeSpan> DelayTimeETA { get; set; }
        public string ReasonForDelay { get; set; }
        public Nullable<bool> OnTheWay { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
